In [1]:
import pandas as pd
import re
import numpy as np
from sklearn.utils import shuffle
from tqdm import tqdm
import random
from itertools import product

# 1. 데이터 생성 및 전처리 과정

## 1-1 기존 데이터 (user_course에 학과, 과목 삭제 조건 적용)

In [2]:
# data initialization
user_major = {}
category_course = {}
major_category = pd.read_csv('./data/major_category.csv', encoding='CP949', header=None)
major_course={}
userlist=[]
courselist=[]
elelist=[]
ele_course=[]

# hakno re
coursere=re.compile('^[A-Z]{3}\d*')

# category, deluniv input
with open('./data/catlist.txt', encoding='UTF-8') as f:
    valid_category = [cate.split("\t")[0] for cate in f.readlines()]
with open('./data/elelist.txt', encoding='UTF-8') as f:
    elelist = [cate.split("\t")[0] for cate in f.readlines()]
with open('./data/deluniv.txt', encoding='UTF-8') as f:
    deluniv = [univ[:-1] for univ in f.readlines()]
    
# data creation
user_course = pd.read_csv('./data/course_userdata.csv', low_memory=False, header=None)
for row in user_course.values:
    if (row[1] in deluniv or str(row[4]) not in valid_category or re.match(coursere, row[5]) == None):
        continue
    user = row[0]
    major = row[1] + '_' + row[2]
    category = row[4]
    course = re.search(coursere, row[5]).group()
    year = row[6]
    term = row[7]
    if user not in user_major:
        user_major[user] = [major]
        userlist.append(user)
    elif major not in user_major[user]:
        user_major[user].append(major)

    if category not in category_course:
        category_course[category] = [course]
    elif course not in category_course[category]:
        category_course[category].append(course)

    if (category in elelist and course not in ele_course):
        ele_course.append(course)

    if course not in courselist:
        courselist.append(course)

for row in major_category.values:
    if row[0] not in major_course:
        major_course[row[0]] = category_course[row[1]]
    else:
        major_course[row[0]] += category_course[row[1]]

In [3]:
print(len(user_course))
user_course.head()

1920266

       0       1      2         3   4         5     6  7     8
0  11900    문과대학     사학  현대사회와심리학  26  UF122-09  2003  1  문과대학
1  71964    음악대학    기악과  현대사회와심리학  26  UF122-09  2003  1  문과대학
2  50516  교육과학대학   교육학과  현대사회와심리학  26  UF122-09  2003  1  문과대학
3    232    이과대학  천문우주학  현대사회와심리학  26  UF122-09  2003  1  문과대학
4  71826    공과대학  세라믹공학  현대사회와심리학  26  UF122-09  2003  1  문과대학

## 1-2 학습을 위한 추가 전처리

In [4]:
# 데이터 수정을 위해 컬럼명 지정
user_course.columns = ['a','b','c','d','e','f','g','h','i']

#a:삭제 대상 학과, b:고려대상 과목, c:조건에 해당하는 user, d:15,16,17년도 각각 조건 적용
a = ~user_course.b.isin(deluniv)
b = user_course.f.str.contains(coursere)
c = user_course.a.isin(userlist)
d = user_course.g.isin([2015,2016,2017])
user_course = user_course[a & b & c & d]

#j 컬럼에 학정번호 앞부분 저장(분반제거) ex) CEE4402-01 > CEE4402
user_course['j'] = user_course['f'].str.findall(coursere)
user_course['j'] = user_course.f.str.split('-').str[0]
user_course = user_course[user_course['j'].isin(courselist)]

#17-2에 수업 들었던 학생(user_20172), 15,16,17-1에 수업 들었던 학생(user_left)
#17년 2월에 수업 들었던 학생 중 나머지 학기에도 들었던 학생(user_fit)리스트 저장
user_20172 = list(set(user_course[(user_course['g'] == 2017) & (user_course['h'] == 2)]['a'].tolist()))
user_left = list(set(user_course[~((user_course['g'] == 2017) & (user_course['h'] == 2))]['a'].tolist()))
user_fit = []
for i in user_20172:
    if i in user_left:
        user_fit.append(i)

#user_fit에 해당하는 학생들의 데이터만 남겨서 user_course에 filtering
user_course = user_course[user_course.a.isin(user_fit)]
        
#2017년 2학기 개강한 수업(course_20172_list)
course_20172_list = list(set(user_course[(user_course['g'] == 2017) & (user_course['h'] == 2)]['j'].tolist()))

print("17-2에 수업 들었던 학생 : {}".format(len(user_20172)))
print("15,16,17-1에 수업 들었던 학생 : {}".format(len(user_left)))
print("17년 2월에 수업 들었던 학생 중 나머지 학기에도 들었던 학생 : {}".format(len(user_fit)))

17-2에 수업 들었던 학생 : 12271
15,16,17-1에 수업 들었던 학생 : 26906
17년 2월에 수업 들었던 학생 중 나머지 학기에도 들었던 학생 : 12031

In [5]:
# user_course (1920266 > 285482)
print(len(user_course))
user_course.head()

285482

,a,b,c,d,e,f,g,h,i,j
564948,154440,공과대학,토목·환경공학,구조시스템설계,179,CEE4402-01,2015,1,토목환경공학전공,CEE4402
564964,139425,공과대학,토목·환경공학,구조시스템설계,179,CEE4402-01,2015,1,토목환경공학전공,CEE4402
564969,190801,공과대학,화공생명공학,공학수학(3),179,MAT2016-07,2015,1,토목환경공학전공,MAT2016
564973,189376,공과대학,기계공학,공학수학(3),179,MAT2016-07,2015,1,토목환경공학전공,MAT2016
564975,188577,공과대학,토목·환경공학,공학수학(3),179,MAT2016-07,2015,1,토목환경공학전공,MAT2016

# 2. NCF 학습

## 2-1 학습 데이터 생성

user_course['user_id'] = user_course['a'].astype("category").cat.codes
user_course['item_id'] = user_course['j'].astype("category").cat.codes
df_to_node2vec = user_course[['a','b','c','d','j','i','g','h','user_id','item_id']].copy()
df_to_node2vec.columns = ['user', 'major1', 'major2', 'item_name', 'item_num', 'item_major', 'year', 'semester', 'user_id', 'item_id']
df_to_node2vec = df_to_node2vec.reset_index(drop=True)

##### 데이터 전달
df_to_node2vec.to_csv('./data/df_to_node2vec.csv',encoding="CP949")

In [6]:
user_course_inter_df = user_course[['a','j','g','h']].copy()
user_course_inter_df.columns = ['user','item','year','sem']
user_course_inter_df = user_course_inter_df.reset_index(drop=True)

# item_id 부여 + user_id column 추가
user_course_inter_df['user_id'] = user_course_inter_df['user'].astype("category").cat.codes
user_course_inter_df['item_id'] = user_course_inter_df['item'].astype("category").cat.codes

users = list(np.sort(user_course_inter_df.user_id.unique()))
items = list(np.sort(user_course_inter_df.item_id.unique()))

user_course_train = user_course_inter_df[~((user_course_inter_df['year'] == 2017) & (user_course_inter_df['sem'] == 2))]
user_course_test = user_course_inter_df[(user_course_inter_df['year'] == 2017) & (user_course_inter_df['sem'] == 2)]

print("# of train users : {}".format(len(users)))
print("# of train items : {}".format(len(items)))
print("# of interactions : {}".format(len(user_course_inter_df)))


print("train inter : {}".format(len(user_course_train)))
print("test inter : {}".format(len(user_course_test)))

# of train users : 12031
# of train items : 2987
# of interactions : 285482
train inter : 220708
test inter : 64774

## 2-2 negative case 생성

In [7]:
import random

In [8]:
neg_num=4
neg_full_u = []
neg_full_i = []

for u in tqdm(users):
    train_num = len(user_course_train[user_course_train['user_id']==u])
    full = {i for i in range(len(items))}
    asis = set(user_course_inter_df[user_course_inter_df['user_id']==u]['item_id'].tolist())
    
    temp_neg_u = [u for i in range(train_num*neg_num)]
    temp_neg_i = random.sample(list(full-asis), train_num*neg_num)
    
    neg_full_u.extend(temp_neg_u)
    neg_full_i.extend(temp_neg_i)

100%|███████████████████████████████████████████████████████████████████████████| 12031/12031 [00:16<00:00, 723.69it/s]

## 2-3 train_df 만들기

In [9]:
u_df = user_course_train['user_id'].tolist()
u_df.extend(neg_full_u)

i_df = user_course_train['item_id'].tolist()
i_df.extend(neg_full_i)

p_df = [1 for i in range(len(user_course_train))]
p_df.extend([0 for i in range(len(neg_full_u))])

print(len(u_df),len(i_df),len(p_df))

train_df = pd.DataFrame({'user_id':u_df, 'item_id':i_df, 'plays':p_df})

1103540 1103540 1103540

## 모델 인풋 생성 + shuff

In [10]:
# train user, item 리스트 생성
rows = train_df['user_id'].astype(int)
cols = train_df['item_id'].astype(int)
values = list(train_df.plays)

uids = np.array(rows.tolist())
iids = np.array(cols.tolist())

user_input = uids.tolist()
item_input = iids.tolist()
labels = values

user_data_shuff, item_data_shuff, label_data_shuff = shuffle(user_input, item_input, labels)
user_data_shuff = np.array(user_data_shuff).reshape(-1,1)
item_data_shuff = np.array(item_data_shuff).reshape(-1,1)
label_data_shuff = np.array(label_data_shuff).reshape(-1,1)

print(len(user_data_shuff))
print(len(item_data_shuff))
print(len(label_data_shuff))

1103540
1103540
1103540

In [11]:
user_course_train

          user     item  year  sem  user_id  item_id
0       154440  CEE4402  2015    1      258      430
1       139425  CEE4402  2015    1      173      430
2       190801  MAT2016  2015    1     2206     1795
3       189376  MAT2016  2015    1     1922     1795
4       188577  MAT2016  2015    1     1617     1795
...        ...      ...   ...  ...      ...      ...
283360  323663  UCB1104  2017    1     9852     2880
283361  350112  UCB1104  2017    1    11962     2880
283362  348964  UCB1104  2017    1    11808     2880
283363  348965  UCB1104  2017    1    11809     2880
285481  190482  YCA1103  2015    1     2164     2962

[220708 rows x 6 columns]

# 모델

In [12]:
from model.NeuMF import NeuMF

In [ ]:
nmf32 = NeuMF(len(users), len(items), emb_size=32)
model=nmf32.get_model()

In [30]:
model.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_1 (InputLayer)            [(None, 1)]          0
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 1)]          0
__________________________________________________________________________________________________
embedding_2 (Embedding)         (None, 1, 32)        384992      input_1[0][0]
__________________________________________________________________________________________________
embedding_3 (Embedding)         (None, 1, 32)        95584       input_2[0][0]
__________________________________________________________________________________________________
flatten_2 (Flatten)             (None, 32)           0           embedding_2[0][0]
__________________________________________________________________________________________________
flatten_3 (Flatten)             (None, 32)           0           embedding_3[0][0]
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 64)           0           flatten_2[0][0]
                                                                 flatten_3[0][0]
__________________________________________________________________________________________________
dropout (Dropout)               (None, 64)           0           concatenate[0][0]
__________________________________________________________________________________________________
mlp_layer1 (Dense)              (None, 64)           4160        dropout[0][0]
__________________________________________________________________________________________________
dropout1 (Dropout)              (None, 64)           0           mlp_layer1[0][0]
__________________________________________________________________________________________________
batch_norm1 (BatchNormalization (None, 64)           256         dropout1[0][0]
__________________________________________________________________________________________________
mlp_layer2 (Dense)              (None, 32)           2080        batch_norm1[0][0]
__________________________________________________________________________________________________
dropout2 (Dropout)              (None, 32)           0           mlp_layer2[0][0]
__________________________________________________________________________________________________
embedding (Embedding)           (None, 1, 32)        384992      input_1[0][0]
__________________________________________________________________________________________________
embedding_1 (Embedding)         (None, 1, 32)        95584       input_2[0][0]
__________________________________________________________________________________________________
batch_norm2 (BatchNormalization (None, 32)           128         dropout2[0][0]
__________________________________________________________________________________________________
flatten (Flatten)               (None, 32)           0           embedding[0][0]
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 32)           0           embedding_1[0][0]
__________________________________________________________________________________________________
mlp_layer3 (Dense)              (None, 16)           528         batch_norm2[0][0]
__________________________________________________________________________________________________
multiply (Multiply)             (None, 32)           0           flatten[0][0]
                                                                 flatten_1[0][0]
__________________________________________________________________________________________________
mlp_layer4 (Dense)              (None, 8)            136         mlp_layer3[0][0]
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 40)           0           multiply[0][0]
                                                                 mlp_layer4[0][0]
__________________________________________________________________________________________________
output_layer (Dense)            (None, 1)            41          concatenate_1[0][0]
==================================================================================================
Total params: 968,481
Trainable params: 968,289
Non-trainable params: 192
__________________________________________________________________________________________________

In [13]:
model.fit([user_data_shuff, item_data_shuff], label_data_shuff, epochs=20,
               batch_size=256, verbose=1)

Tensor("flatten/Reshape:0", shape=(None, 32), dtype=float32)
Tensor("flatten_1/Reshape:0", shape=(None, 32), dtype=float32)
Tensor("flatten_2/Reshape:0", shape=(None, 32), dtype=float32)
Tensor("flatten_3/Reshape:0", shape=(None, 32), dtype=float32)
Epoch 1/20
4311/4311 [==============================] - 29s 7ms/step - loss: 0.3866
Epoch 2/20
4311/4311 [==============================] - 29s 7ms/step - loss: 0.1782
Epoch 3/20
4311/4311 [==============================] - 29s 7ms/step - loss: 0.1209
Epoch 4/20
4311/4311 [==============================] - 30s 7ms/step - loss: 0.0967
Epoch 5/20
4311/4311 [==============================] - 30s 7ms/step - loss: 0.0818
Epoch 6/20
4311/4311 [==============================] - 29s 7ms/step - loss: 0.0712
Epoch 7/20
4311/4311 [==============================] - 28s 7ms/step - loss: 0.0623
Epoch 8/20
4311/4311 [==============================] - 28s 6ms/step - loss: 0.0558
Epoch 9/20
4311/4311 [==============================] - 28s 7ms/step - loss: 0.0511
Epoch 10/20
4311/4311 [==============================] - 28s 6ms/step - loss: 0.0478
Epoch 11/20
4311/4311 [==============================] - 28s 6ms/step - loss: 0.0461
Epoch 12/20
4311/4311 [==============================] - 28s 6ms/step - loss: 0.0454
Epoch 13/20
4311/4311 [==============================] - 28s 6ms/step - loss: 0.0451
Epoch 14/20
4311/4311 [==============================] - 28s 6ms/step - loss: 0.0449
Epoch 15/20
4311/4311 [==============================] - 29s 7ms/step - loss: 0.0448
Epoch 16/20
4311/4311 [==============================] - 28s 6ms/step - loss: 0.0448
Epoch 17/20
4311/4311 [==============================] - 28s 7ms/step - loss: 0.0447
Epoch 18/20
4311/4311 [==============================] - 29s 7ms/step - loss: 0.0447
Epoch 19/20
4311/4311 [==============================] - 29s 7ms/step - loss: 0.0447
Epoch 20/20
4311/4311 [==============================] - 28s 6ms/step - loss: 0.0447

# Predict

In [14]:
user_dict = dict(zip(user_course_inter_df['user'].tolist(), user_course_inter_df['user_id'].tolist()))
item_dict = dict(zip(user_course_inter_df['item'].tolist(), user_course_inter_df['item_id'].tolist()))

In [15]:
model.save('./pretrain/ncf32-base.h5')

In [26]:
def predict_return(u, K):
    user=user_course_inter_df[user_course_inter_df['user_id']==u]['user'].iloc[0]

    full = set(user_course_test['item_id'].tolist())
    asis = set(user_course_train[user_course_train['user_id']==u]['item_id'].tolist())
    pred_cand_list = list(full-asis)
    #print(len(full),len(asis),len(pred_cand_list))
    pred_user_list = [u for i in range(len(pred_cand_list))]

    pred_user = np.array(pred_user_list).reshape(-1,1)
    pred_cand = np.array(pred_cand_list).reshape(-1,1)

    # predict 진행
    predictions = model.predict([pred_user, pred_cand])
    predictions = predictions.flatten().tolist()

    pred_dict = dict(zip(pred_cand_list, predictions))
    pred_df = pd.DataFrame({'item':pred_cand_list, 'score':predictions})

    # 유저에 해당되는 전공 과목 리스트 가져옴
    temp_user_major = major_course[user_major[user][0]]
    for i in range(len(temp_user_major)):
        try:
            temp_user_major[i] = item_dict[temp_user_major[i]]
        except:
            pass
    #temp_user_major = list(map(lambda x:item_dict[x],temp_user_major))

    # 전공, 비전공 분류
    req_df = pred_df[pred_df['item'].isin(temp_user_major)]
    fre_df = pred_df[~pred_df['item'].isin(temp_user_major)]

    # 예측결과 정렬해서 list 형태 출력
    req_list = req_df.sort_values(by='score',ascending=False)['item'].tolist()
    fre_list = fre_df.sort_values(by='score',ascending=False)['item'].tolist()

    return(req_list[0:K], fre_list[0:K])

In [24]:
# user_id, K input으로
predict_return(1,5)

1340 9 1338

([1456, 1450, 1457, 1458, 1459], [2343, 1025, 2384, 19, 2969])

# Evaluate

In [18]:
import numpy as np

def recall_(p,r):
    try:
        return(int(sum(p))/int(len(r)))
    except:
        return(0)

def precision_at_k(r, k):
    assert k >= 1
    r = np.asarray(r)[:k] != 0
    #print(r)
    if r.size != k:
        raise ValueError('Relevance score length < k')
    return np.mean(r)


def average_precision(r):
    r = np.asarray(r) != 0
    out = [precision_at_k(r, k + 1) for k in range(r.size) if r[k]]
    if not out:
        return 0.
    return np.mean(out)


def mean_average_precision(rs):
    return np.mean([average_precision(r) for r in rs])

def dcg_at_k(r, k, method=0):
    r = np.asfarray(r)[:k]
    if r.size:
        if method == 0:
            return r[0] + np.sum(r[1:] / np.log2(np.arange(2, r.size + 1)))
        elif method == 1:
            return np.sum(r / np.log2(np.arange(2, r.size + 2)))
        else:
            raise ValueError('method must be 0 or 1.')
    return 0.

def ndcg_at_k(r, k=20, method=1):
    dcg_max = dcg_at_k(sorted(r, reverse=True), k, method)
    if not dcg_max:
        return 0.
    return dcg_at_k(r, k, method) / dcg_max

In [19]:
def asis_return(u):
    user=user_course_inter_df[user_course_inter_df['user_id']==u]['user'].iloc[0]

    # 유저에 해당되는 전공 과목 리스트 가져옴
    temp_user_major = major_course[user_major[user][0]]
    for i in range(len(temp_user_major)):
        try:
            temp_user_major[i] = item_dict[temp_user_major[i]]
        except:
            pass
    #temp_user_major = list(map(lambda x:item_dict[x],temp_user_major))

    temp_asis_df = user_course_test[user_course_test['user_id']==u].copy()

    req_asis = temp_asis_df[temp_asis_df['item_id'].isin(temp_user_major)]
    fre_asis = temp_asis_df[~temp_asis_df['item_id'].isin(temp_user_major)]

    return(req_asis['item_id'].tolist(), fre_asis['item_id'].tolist())

In [20]:
# user_id 만 집어넣음
asis_return(1)

([1540, 1514, 1506, 1484, 1459, 1492], [2980, 1026])

In [22]:
for i in range(100):
    eval_gt = asis_return(i)
    eval_pred = predict_return(i,10)

    print('\n[user {}]'.format(i))
    print("-req-")
    print(' gt : ',eval_gt[0])
    print('pred: ',eval_pred[0])


    temp_req=[1 if c in eval_gt[0] else 0 for c in eval_pred[0]]
    print(temp_req)

[user 0]
-req-
 gt :  []
pred:  [2466, 2459, 2476, 2501, 2500, 2487, 2482, 2475, 2508, 2507]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 1]
-req-
 gt :  [1540, 1514, 1506, 1484, 1459, 1492]
pred:  [1456, 1450, 1457, 1458, 1459, 1482, 1484, 1465, 1500, 1476]
[0, 0, 0, 0, 1, 0, 1, 0, 0, 0]

[user 2]
-req-
 gt :  [2738, 2743]
pred:  [2738, 2735, 2729, 2720, 2743, 2721, 2715, 2730, 2727, 2728]
[1, 0, 0, 0, 1, 0, 0, 0, 0, 0]

[user 3]
-req-
 gt :  []
pred:  [2400, 2393, 2351, 2359, 2389, 2380, 2378, 2379, 2358, 2344]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 4]
-req-
 gt :  [2650]
pred:  [2645, 2664, 2680, 2658, 2648, 2663, 2661, 2678, 2683, 2652]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 5]
-req-
 gt :  [1950, 1949, 1948, 1947, 1946, 1943, 1942]
pred:  [1926, 1918, 1898, 1966, 1965, 1919, 1913, 1907, 1921, 1912]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 6]
-req-
 gt :  []
pred:  [1361, 1351, 1373, 1366, 1355, 1360, 1359, 2869, 1352, 1371]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 7]
-req-
 gt :  []
pred:  [2750, 2553, 2554, 1791, 2556]
[0, 0, 0, 0, 0]

[user 8]
-req-
 gt :  [199, 194]
pred:  [193, 199, 194, 200, 198, 201, 288, 305, 284, 226]
[0, 1, 1, 0, 0, 0, 0, 0, 0, 0]

[user 9]
-req-
 gt :  [192, 186, 1783]
pred:  [184, 2750, 1781, 187, 177, 1782, 174, 183, 178, 190]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 10]
-req-
 gt :  [1794, 435, 431, 429, 428]
pred:  [1793, 1265, 1260, 431, 429, 426, 407, 418, 415, 1252]
[0, 0, 0, 1, 1, 0, 0, 0, 0, 0]

[user 11]
-req-
 gt :  []
pred:  [1735, 1737, 1718]
[0, 0, 0]

[user 12]
-req-
 gt :  [1074]
pred:  [1024, 1023, 1025, 1049, 1047, 1038, 1069, 1052, 1032, 1034]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 13]
-req-
 gt :  [2554, 1791, 1815, 1820]
pred:  [2553, 1806, 1807, 2750, 1818, 1809, 1800, 2554, 1817, 1811]
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]

[user 14]
-req-
 gt :  [1043, 1032]
pred:  [1047, 1032, 1049, 1051, 1050, 1074, 1038, 1040, 1028, 1045]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]

[user 15]
-req-
 gt :  [2061]
pred:  [2021, 2023, 2017, 2014, 2026, 2016, 2025, 2019, 2020, 2011]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 16]
-req-
 gt :  [1053, 1049, 1032]
pred:  [1038, 1024, 1050, 1025, 1034, 1052, 1044, 1062, 1040, 1075]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 17]
-req-
 gt :  []
pred:  [193, 200, 199, 220, 194, 216, 283, 273, 286, 215]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 18]
-req-
 gt :  [1546]
pred:  [1371, 1360, 1373, 1372, 2869, 1352, 1359, 1345, 1546, 1363]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0]

[user 19]
-req-
 gt :  [2790, 2763, 2751]
pred:  [2814, 2772, 2781, 2830, 2790, 2862, 2807, 2756, 2763, 2826]
[0, 0, 0, 0, 1, 0, 0, 0, 1, 0]

[user 20]
-req-
 gt :  []
pred:  [1554, 1259, 1266, 1248, 1551, 1555, 1264, 1263, 1795, 1570]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 21]
-req-
 gt :  []
pred:  [426, 407, 409, 431, 1796, 415, 434, 1257, 429, 418]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 22]
-req-
 gt :  [1762]
pred:  [1768, 1745, 1767, 1762, 1755, 1756, 1776, 1771, 1752, 1747]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]

[user 23]
-req-
 gt :  [1438]
pred:  [1422, 1432, 1419, 1431, 1420, 1435, 1415, 1424, 1416, 1414]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 24]
-req-
 gt :  [1730]
pred:  [1737, 1730, 1718]
[0, 1, 0]

[user 25]
-req-
 gt :  [1813]
pred:  [1264, 1795, 1263, 1266, 1248, 1796, 1265, 1794, 1259, 1260]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 26]
-req-
 gt :  [269]
pred:  [194, 199, 200, 193, 210, 198, 252, 230, 207, 211]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 27]
-req-
 gt :  [1045]
pred:  [1027, 1023, 1028, 1049, 1032, 1024, 1050, 1053, 1034, 1065]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 28]
-req-
 gt :  [2061, 2021]
pred:  [1248, 1266, 1264, 2017, 2023, 2019, 2014, 2025, 2020, 1265]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 29]
-req-
 gt :  [1256, 1152, 1150]
pred:  [1139, 1143, 1257, 1141, 1137, 1813, 1793, 1151, 1795, 1142]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 30]
-req-
 gt :  [1796, 435, 434]
pred:  [426, 1260, 431, 1796, 1261, 1264, 1265, 415, 1257, 1259]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]

[user 31]
-req-
 gt :  [1151, 1151]
pred:  [1138, 1179, 1150, 1140, 1137, 1152, 1796, 1146, 1155, 1151]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1]

[user 32]
-req-
 gt :  []
pred:  [1028, 1027, 1049, 1023, 1047, 1025, 1038, 1024, 1053, 1032]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 33]
-req-
 gt :  []
pred:  [726, 695, 688, 684, 691, 716, 685, 686, 705, 704]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 34]
-req-
 gt :  [2730, 2727, 2726, 2723, 2729]
pred:  [2729, 2727, 2743, 2730, 2728, 2726, 2742, 2718, 2739, 2723]
[1, 1, 0, 1, 0, 1, 0, 0, 0, 1]

[user 35]
-req-
 gt :  [1730]
pred:  [1735, 1737, 1730, 1718]
[0, 0, 1, 0]

[user 36]
-req-
 gt :  []
pred:  [1735, 1730, 1737, 1718]
[0, 0, 0, 0]

[user 37]
-req-
 gt :  [2339, 2331, 2322, 2338]
pred:  [2316, 2331, 2553, 2318, 2554, 2322, 2341, 2335, 2556, 2339]
[0, 1, 0, 0, 0, 1, 0, 0, 0, 1]

[user 38]
-req-
 gt :  [1730]
pred:  [1735, 1737, 1718]
[0, 0, 0]

[user 39]
-req-
 gt :  [2672, 2648, 2650]
pred:  [2646, 2645, 2648, 2668, 2672, 2678, 2662, 2658, 2652, 2650]
[0, 0, 1, 0, 1, 0, 0, 0, 0, 1]

[user 40]
-req-
 gt :  []
pred:  [1737, 1718]
[0, 0]

[user 41]
-req-
 gt :  [1730]
pred:  [1737, 1718]
[0, 0]

[user 42]
-req-
 gt :  [1730]
pred:  [1737, 1718]
[0, 0]

[user 43]
-req-
 gt :  [1228, 1186]
pred:  [1185, 1186, 1217, 1182, 1181, 1228, 1210, 1212, 1234, 1221]
[0, 1, 0, 0, 0, 1, 0, 0, 0, 0]

[user 44]
-req-
 gt :  [2684, 2662, 2652, 2648]
pred:  [2683, 2684, 2661, 2662, 2663, 2680, 2658, 2678, 2672, 2686]
[0, 1, 0, 1, 0, 0, 0, 0, 0, 0]

[user 45]
-req-
 gt :  [2501, 2476, 2475, 2490]
pred:  [2459, 2466, 2501, 2476, 2490, 2508, 2473, 2481, 2487, 2475]
[0, 0, 1, 1, 1, 0, 0, 0, 0, 1]

[user 46]
-req-
 gt :  [1074, 1052]
pred:  [1052, 1023, 1025, 1032, 1024, 1050, 1040, 1074, 1062, 1034]
[1, 0, 0, 0, 0, 0, 0, 1, 0, 0]

[user 47]
-req-
 gt :  []
pred:  [1796, 407, 409, 426, 1257, 431, 1264, 418, 1266, 415]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 48]
-req-
 gt :  [1005]
pred:  [975, 992, 1000, 994, 995, 988, 997, 996, 1005, 1016]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0]

[user 49]
-req-
 gt :  [1573]
pred:  [1554, 1257, 1261, 1795, 1553, 1248, 1259, 1552, 1551, 1555]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 50]
-req-
 gt :  [2443]
pred:  [2416, 2421, 2424, 2443, 2436, 2420, 2457, 2417, 2439, 2429]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]

[user 51]
-req-
 gt :  [1794, 1999]
pred:  [1979, 1973, 1987, 1988, 1986, 1990, 1974, 1994, 1992, 1991]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 52]
-req-
 gt :  []
pred:  [1737, 1735, 1718]
[0, 0, 0]

[user 53]
-req-
 gt :  [1138]
pred:  [1150, 1179, 1152, 1155, 1139, 1151, 1138, 1257, 1146, 1264]
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0]

[user 54]
-req-
 gt :  []
pred:  [1028, 1049, 1024, 1023, 1047, 1053, 1032, 1038, 1034, 1050]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 55]
-req-
 gt :  []
pred:  [1028, 1027, 1024, 1025, 1023, 1049, 1032, 1047, 1053, 1050]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 56]
-req-
 gt :  [1149]
pred:  [1137, 1795, 1140, 1139, 1143, 1151, 1257, 1152, 1248, 1155]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 57]
-req-
 gt :  [1252, 1794]
pred:  [779, 782, 783, 780, 781, 1794, 1257, 1793, 787, 1264]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]

[user 58]
-req-
 gt :  [2061, 2056, 2028]
pred:  [2017, 2021, 2023, 1257, 2042, 2020, 2008, 2059, 2044, 2025]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 59]
-req-
 gt :  [2326, 2338]
pred:  [1791, 2322, 2326, 2554, 2556, 2341, 2335, 2316, 2750, 2339]
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

[user 60]
-req-
 gt :  []
pred:  [2686, 729, 694, 719, 685, 734, 705, 713, 691, 699]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 61]
-req-
 gt :  [2466]
pred:  [2501, 2473, 2475, 2466, 2490, 2500, 2476, 2459, 2507, 2506]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]

[user 62]
-req-
 gt :  [2532]
pred:  [2536, 2509, 2514, 2537, 2512, 2515, 2525, 2546, 2535, 2523]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 63]
-req-
 gt :  [969, 965, 964, 963, 962, 961, 960, 959, 958, 956, 955, 954, 953, 948, 944, 957, 968]
pred:  [891, 879, 878, 940, 969, 953, 873, 958, 872, 870]
[0, 0, 0, 0, 1, 1, 0, 1, 0, 0]

[user 64]
-req-
 gt :  [2712, 2702, 2700, 2691, 2711]
pred:  [2706, 2704, 2700, 2699, 2702, 2686, 2711]
[0, 0, 1, 0, 1, 0, 1]

[user 65]
-req-
 gt :  []
pred:  [2814, 2807, 2781, 2772, 2830, 2862, 2756, 2790, 2826, 2823]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 66]
-req-
 gt :  [2490, 2466]
pred:  [2459, 2466, 2476, 2501, 2490, 2462, 2482, 2507, 2475, 2460]
[0, 1, 0, 0, 1, 0, 0, 0, 0, 0]

[user 67]
-req-
 gt :  [2495]
pred:  [2459, 2500, 2490, 2482, 2485, 2487, 2508, 2460, 2473, 2506]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 68]
-req-
 gt :  [269, 207, 196, 194, 209, 227]
pred:  [200, 199, 210, 193, 198, 207, 215, 269, 219, 229]
[0, 0, 0, 0, 0, 1, 0, 1, 0, 0]

[user 69]
-req-
 gt :  [2495]
pred:  [2501, 2459, 2466, 2469, 2490, 2485, 2482, 2462, 2487, 2460]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 70]
-req-
 gt :  []
pred:  [1257, 1261, 1264, 1552, 1554, 1266, 1796, 1248, 1571, 1793]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 71]
-req-
 gt :  []
pred:  [2751, 2814, 2790, 2781, 2756, 2807, 2772, 2862, 2830, 2763]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 72]
-req-
 gt :  []
pred:  [1257, 1264, 1266, 1265, 1263, 1261, 1248, 1796, 407, 417]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 73]
-req-
 gt :  []
pred:  [210, 199, 193, 252, 200, 194, 215, 233, 227, 229]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 74]
-req-
 gt :  [1531, 1514, 1484, 1482]
pred:  [1450, 1456, 1458, 1457, 1476, 1482, 1463, 1500, 1459, 1468]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]

[user 75]
-req-
 gt :  []
pred:  [2536, 2537, 2548, 2515, 2523, 2509, 2512, 2514, 2535, 2546]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 76]
-req-
 gt :  [1005, 1015, 988, 984, 983]
pred:  [988, 994, 984, 997, 974, 1010, 975, 996, 1015, 983]
[1, 0, 1, 0, 0, 0, 0, 0, 1, 1]

[user 77]
-req-
 gt :  [223]
pred:  [220, 193, 200, 210, 198, 230, 194, 312, 199, 201]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 78]
-req-
 gt :  [1256, 1178, 1166]
pred:  [1139, 1137, 1257, 1141, 1796, 1140, 1795, 1142, 1179, 1152]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 79]
-req-
 gt :  [1263, 824, 837, 851]
pred:  [1796, 826, 1263, 848, 833, 1795, 824, 1261, 1257, 1813]
[0, 0, 1, 0, 0, 0, 1, 0, 0, 0]

[user 80]
-req-
 gt :  [1950, 1949, 1948, 1947, 1946, 1943, 1942]
pred:  [1893, 1881, 1884, 1894, 1885, 1887, 1883, 1897, 1879, 1895]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 81]
-req-
 gt :  [591, 577, 590]
pred:  [567, 588, 571, 597, 570, 596, 569, 589, 2853, 577]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1]

[user 82]
-req-
 gt :  [2739]
pred:  [2730, 2738, 2729, 2728, 2739, 2727, 2736, 2715, 2722, 2742]
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]

[user 83]
-req-
 gt :  [210, 201]
pred:  [201, 210, 229, 219, 221, 283, 273, 215, 225, 242]
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]

[user 84]
-req-
 gt :  []
pred:  [1795, 1257, 1264, 1259, 1813, 1261, 1263, 89, 41, 49]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 85]
-req-
 gt :  [428]
pred:  [1261, 428, 434, 429, 1260, 1265, 1248, 1259, 1794, 1266]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]

[user 86]
-req-
 gt :  []
pred:  [779, 782, 780, 783, 1793, 1794, 781, 792, 791, 795]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 87]
-req-
 gt :  [1815, 1814, 1798]
pred:  [1806, 1807, 2553, 1817, 2750, 1818, 1809, 1798, 1823, 1825]
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]

[user 88]
-req-
 gt :  [1005, 984, 1003]
pred:  [996, 995, 975, 984, 974, 1005, 1010, 1015, 1016, 983]
[0, 0, 0, 1, 0, 1, 0, 0, 0, 0]

[user 89]
-req-
 gt :  [311, 219, 207, 223, 210, 206]
pred:  [210, 194, 198, 193, 200, 230, 252, 201, 199, 216]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 90]
-req-
 gt :  [230, 213, 214]
pred:  [252, 201, 227, 230, 200, 194, 199, 216, 242, 193]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]

[user 91]
-req-
 gt :  [284]
pred:  [210, 230, 252, 227, 193, 216, 212, 201, 273, 215]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 92]
-req-
 gt :  [214]
pred:  [210, 215, 194, 198, 196, 209, 252, 199, 269, 200]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 93]
-req-
 gt :  []
pred:  [193, 200, 210, 194, 198, 199, 201, 220, 233, 222]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 94]
-req-
 gt :  [284, 269, 268, 265, 209]
pred:  [194, 199, 193, 210, 201, 200, 198, 252, 216, 215]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[user 95]
-req-
 gt :  [1796, 1573, 1571, 1564, 1562, 1566]
pred:  [1257, 1264, 1261, 1796, 1554, 1552, 1266, 1573, 1265, 1571]
[0, 0, 0, 1, 0, 0, 0, 1, 0, 1]

[user 96]
-req-
 gt :  [1263, 1813, 844, 851, 838]
pred:  [821, 1264, 1263, 1795, 822, 831, 826, 1261, 1796, 1248]
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

[user 97]
-req-
 gt :  [1813, 1796, 1796, 49]
pred:  [1264, 1257, 1259, 1795, 49, 63, 1261, 50, 56, 69]
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]

[user 98]
-req-
 gt :  [1261, 85, 84, 69]
pred:  [41, 50, 42, 63, 69, 43, 1795, 49, 89, 56]
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]

[user 99]
-req-
 gt :  [2059, 2044, 2011]
pred:  [2021, 2026, 2019, 2023, 2016, 2014, 1264, 2017, 2011, 2025]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0]

In [28]:
p=[]
r=[]

for i in tqdm(range(12031)):
    eval_gt = asis_return(i)
    eval_pred = predict_return(i,10) # pred개수

    temp_req=[1 if c in eval_gt[0] else 0 for c in eval_pred[0]]
    #temp_pre=[1 if c in eval_gt[1] else 0 for c in eval_pred[1]]

    #precision_at_k(temp_req,10)
    
    # 앞에 temp, 뒤에 gt
    #recall_(temp_req, eval_gt[0])
    if eval_gt[0] != []:
        p.append(precision_at_k(temp_req,len(temp_req)))
        r.append(recall_(temp_req, eval_gt[0]))

100%|████████████████████████████████████████████████████████████████████████████| 12031/12031 [14:28<00:00, 13.85it/s]

In [29]:
print(sum(p)/len(p))
print(sum(r)/len(r))

0.25391822377381473
0.6276630856462504